# Generated by Django 5.2.3 on 2025-07-17 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
                ("rating_score", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "fragrance_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="perfume_images/")),
                ("official_url", models.URLField(blank=True, null=True)),
                ("season_chart", models.JSONField(blank=True, null=True)),
                ("occasion_chart", models.JSONField(blank=True, null=True)),
                ("type_chart", models.JSONField(blank=True, null=True)),
                ("style_chart", models.JSONField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="slug", max_length=200, unique=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.brand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfumeAccord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.accord"
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.perfume"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfumeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.note"
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.perfume"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_perfume_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unisex", "Unisex"),
                            ("None", "No Preference"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "liked_perfumes",
                    models.ManyToManyField(
                        blank=True, related_name="liked_by", to="main.perfume"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
